### ISSUE TITLE
Physics/Lighting Bug

### ISSUE THREAD

**Issue by Xtronius** [BennyQBD/DareEngine#8] opened 2015-07-03 04:44 UTC
I modified some of the code for this engine because of the fbo issues I had because of my out dated hardware, but I did not change anything with the physics code. When I add a LightComponent for the Entity e2 in the Test scene, it creates these invisible walls along the x and y axis of the edges of the Entity e, only when you move in a certain direction. I have not been able to figure out why this is happening.

**Comment by Xtronius** [comment] 2015-07-03 13:38
This is not a bug. I had messed up the values of the width and height of the light and that caused that issue.

**Comment by BennyQBD** [comment] 2015-07-03 17:57
Actually, I had some brief issues with something like this in an earlier version of the repository, so this is probably a genuine issue. Also, any width/height values for the light should work. Could you tell me what width/height values you had an issue with?

If you're curious, I think the issue because I'm unintentionally still doing some physics things using the entity's AABB rather than the entity's collider AABB. Adding a light will expand the entity's AABB, since the entity is now taking up more space, but because the collider AABB isn't being used consistently in the physics code (in theory), it causes some odd collision artifacts.

**Comment by BennyQBD** [comment] 2015-07-03 18:02
I've confirmed that if you add a LightComponent to e2 with a width of 2.0 and a height of 2.0, then you can go to a corner of the screen, but you can't go into a space directly adjacent to entity 1, even though nothing is blocking it. I'm now working on a fix.

**Comment by Xtronius** [comment] 2015-07-03 18:05
Yes I had those values for the width and height of the LightComponent.

**Comment by BennyQBD** [comment] 2015-07-03 18:06
I've now posted what I believe is a fix for the problem. If you can verify that it works, I think we can close this issue.

**Comment by Xtronius** [comment] 2015-07-03 18:10
That fixed it, thanks.

**Closed** 2015-07-03 18:12 UTC
